[package]
name = "orchestral-reductions"
version = "0.1.0"
authors = ["jmw33"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roxmltree = "0.11.0"
quick-xml = "0.18.1"
clap = "2.33.0"
itertools = "0.9.0"